---
theme: "hyde"
contentdir: "content"
layoutdir: "layouts"
publishdir: "docs"
indexes:
  category: "categories"
baseurl: "https://justasitsounds.github.io/hypnodome/"
title: "Enter the Hypno-dome!"
canonifyurls: true

params:
    themeColor: "theme-base-0b"
    layoutReverse: true
    description: "Something to do"
